## YAML Template.
---
driverDB: com.mysql.jdbc.Driver
##urlDB: jdbc:mysql://db4free.net:3307/clasesdaw?useSSL=false
urlDB: jdbc:mysql://db4free.net:3307/dawivan?useSSL=false
##userDB: oscarnovillo
##passDB: c557ef
userDB: dawivan
passDB: nohay2sin2
##passDB: clasesdaw